#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          24
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#353b45"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar top &

bspc rule -a pavucontrol state=floating
bspc rule -a nitrogen state=floating

